language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
os: windows
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: leonardodiegues
  password:
    secure: YuzUuEOvxw54OR+SGCUq0vJvsggWZV5MC4NvxInjYqdHl5t6jkZ59p4QozgwJJofQoe6sqFEVYVdPv9yZmOB/nE0vL8X89/vLB2cluAkY7NMlMlsPr9EIPc70wAluGfRkDb8KowXnmbySOhOPkcJ27TAWs0j1JJVi3UNxFy/KpP3DBoRTKbEOAPpCecoug+QkGRxpxpG7KP9GJldyXzi7DEsx0LasGpYKG1wDyycjXGhAHJY+mXFNl0TOm8Bph3CDr1t9ACgKNtR0bFcu4wNgJyL3ZnRVDHYlGVJXVnNuQKZYX11rkpe22K6H3seN37lEqdEEEqZQTsphXb0xQdpKHz6N3CCCCJAOAE2ekKhwXXtahXIGIWinBXLQLUK0eL5VT3/VOft+6G4ShZVyahCnr+UCKlv6bee7LqMdKQHukuSHn6GQaKCZVMQC5xapgYgrcCeUidL3qDLG/uAr4ZVDz/W6EuKhsf2aq7dWA0CFsrsxllohMLxw4aA4jGwfS8nATTNn3cG5MGLPCHBJIF0hG8x4sQ9oUo3Q+fgiHaIxhZE8I2q6M7ABvO0qMw7Ruas+gZZ1b4HSZHcvyxaqa7I5o+LPg9NIW5wughlceKkN3RV2sL1BNtjZlW7FJ0FMEyLJEW/H0Szd3lu/BSCM4yOEpYylpaDSTRFBZDnmvzUq+4=
  on:
    tags: true
    repo: leonardodiegues/minrest
    python: 3.8
